### ISSUE TITLE
The "Investments" tab on pool pages data dsiplay glitch

### ISSUE THREAD

**Issue by 0xKang** [vertekfi/dex-frontend#28] opened 2023-01-26 12:48 UTC
![image](https://user-images.githubusercontent.com/106936065/214838950-67a716c3-d7f8-4670-b668-7893dccde463.png)

The data that this tab displays is bugged, it keeps repeating the same 3 txns. Each txn should only show once, sorted with most recent at the top.

It doesnt happen immediately when u open the page, but if u click load more and wait a bit, it turns into this (see image). Might be reading the data over and over again.

**Comment by harleen-m** [comment] 2023-01-26 12:59
Interesting! I cannot easily reproduce it. I tried clicking on Load More and nothing happened. I was able to reproduce it only twice and I still have no idea what I exactly did.

**Comment by jumpman23xx** [comment] 2023-02-02 13:48
Closing this because I cant reproduce either, but will continue to monitor

**Closed by jumpman23xx** 2023-02-02 13:48 UTC

**Comment by harleen-m** [comment] 2023-02-02 15:54
This is unfortunately still happening. One way to reproduce it:

- Open this pool in an incognito tab (doesn't really need to be incognito though). https://www.vertek.exchange/pool/0x25b7dcdccaab62f4cacef8bc9ae20553eb1d9164000000000000000000000008
- Click on Investments
- Click on Swaps
- Click back on Investments
- Wait a bit (30 seconds +-)

I hope it helps at least a bit!
